version: '3.8'

services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    networks:
      - nepNet
    restart: always
    container_name: napcat
    environment:
      - ACCOUNT=2437618725
      - WSR_ENABLE=true
      - WS_URLS=["ws://nonebot:5140/onebot/v11/ws"]

  nonebot:
    build:
      context: ./nonebot
    networks:
      - nepNet
    expose:
      - "5140"
    container_name: nonebot
    volumes:
      - ./nonebot:/app
    command: bash -c "pdm run --venv nonebot spider.py"
        # command: tail -f /dev/null

networks:
  nepNet:
    driver: bridge
